### ISSUE TITLE
Include root folders + close opened finder windows

### ISSUE THREAD

**Issue by Dexnero** [brgmn/fssrt#1]
Hey there, finally I got an solution for an annoying problem – thank you so much. Works fine on 10.10

But two issues:
1) Is it possible to include root folders? Meaning no subfolder on the network share to use as path, I tried modifying your script, but AppleScript is not my case...
2) Close the opened finder window again after adding it to the sidebar?

**Comment by brgmn** [comment]
Hi @Dexnero 

1) sorry, but I think root folders won't work as sidebar shortcut. Maybe you could use a local symlink to emulate rootfolders and use the symlink in fssrt. 
2) What do you mean with "Close the opened finder window again"?

**Comment by Dexnero** [comment]
Hi, when I run the fssrt.app: for every item in my shortcuts.txt a new finder window with the specified folder is opened. But it stays open after everyting is set and done.
